config/routes.rb
Rails.application.routes.draw do
  root "user/time_logs#index"

  resource :admins, only: [:create], controller: "admin/admins" do
    get "signin" => "admin/admins#signin"
    delete "signout" => "admin/admins#signout"
  end

  # for admin
  namespace :admin do
    root "time_logs#index"
    resources :users, only: [:index, :new, :create, :edit, :update] do
      resources :time_logs, only: [:index, :show, :update], shallow: true do
        resources :comments, only: [:create, :update]
      end
    end
  end

  resource :users, only: [:create, :edit, :update], module: :user do
    get "signin" => "users#signin"
    delete "signout" => "users#signout"
  end

  # for logined user
  resources :time_logs, only: [:index, :show, :create, :update], module: :user do
    resources :comments, only: [:create]
  end
end

app/models/time_log.rb
class TimeLog < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :user_comments
  has_many :admin_comments

  validate :not_inversion

  def not_inversion
    errors.add(:base, "終了時刻が開始時刻より前です") if end_at && start_at >= end_at
  end

  def user_updatable?
    original_end_at && non_last?.! && time_up?.!
  end

  def updatable_check(params = nil)
    if params && lengthen?(params)
      errors.add(:base, "延長はできません")
    elsif original_end_at.!
      errors.add(:base, "まだ終了していません")
    elsif non_last?
      errors.add(:base, "変更できるのは最新の打刻だけです")
    elsif time_up?
      errors.add(:base, "変更ができるのは打刻後60分以内です")
    end
  end

  def update_with_create_user_comment(params)
    old_end = self.end_at
    updatable_check(params)
    unless errors.any?
      if update(params)
        user_comments.create(body: "終了時刻を:#{old_end} から #{end_at}に変更しました")
      end
    end
  end

  def update_with_create_admin_comment(params, admin)
    old_end = self.end_at
    if update(params)
      admin_comments.create(admin: admin, body: "#{admin.account}が終了時刻を:#{old_end} から #{end_at}に変更しました")
    end
  end

  private
  def lengthen?(param)
    end_at < Time.zone.local(param["end_at(1i)"], param["end_at(2i)"], param["end_at(3i)"], param["end_at(4i)"], param["end_at(5i)"])
  end

  def non_last?
    self != self.user.time_logs.last
  end

  def time_up?
    Time.zone.now > original_end_at + 1.hour
  end
end

app/controllers/admin/time_logs_controller.rb
class Admin::TimeLogsController < Admin::Base
  def index
    @user = User.find(params[:user_id])
    @target_month = target_month
    @time_logs = @user.time_logs.where(start_at: @target_month.all_month)
  end

  def show
    @time_log = TimeLog.find(params[:id])
  end

  def update
    @time_log = TimeLog.find(params[:id])
    if @time_log.update_with_create_admin_comment(time_log_params, current_admin)
      redirect_to admin_time_log_path(@time_log), { notice: "更新に成功しました" }
    else
      render 'show'
    end
  end

  private
  def time_log_params
    params.require(:time_log).permit(:start_at, :end_at)
  end

  def target_month
    params[:query].try {|q|
      year = q["date(1i)"]
      month = q["date(2i)"]
      Time.zone.local(year, month) if year && month
    } || Time.zone.now
  end
end

app/controllers/time_logs_controller.rb
class TimeLogsController < ApplicationController
  def index
    @time_logs = current_user.time_logs
  end

  def new
  end

  def create
  end

  def update
  end
end

app/controllers/user/time_logs_controller.rb
class User::TimeLogsController < User::Base
  def index
    @user = current_user
    @condition = @user.time_logs.exists?(end_at: nil)
    @target_month = target_month
    @time_logs = @user.time_logs.where(start_at: @target_month.all_month)
  end

  def show
    @time_log = current_user.time_logs.find(params[:id])
    @time_log.updatable_check()
  end

  def create
    time_log = current_user.time_logs.find_or_initialize_by(end_at: nil)
    time = Time.zone.now
    if time_log.start_at
      time_log.update(end_at: time, original_end_at: time)
      SlackBot.notify(body: "#{current_user.name}(#{current_user.account}): Start")
    else
      time_log.update(start_at: time, original_start_at: time)
      SlackBot.notify(body: "#{current_user.name}(#{current_user.account}): Stop...#{(time_log.end_at-time_log.start_at)/60.0}分")
    end
    redirect_to time_logs_path
  end

  def update
    @time_log = current_user.time_logs.find(params[:id])
    if @time_log.update_with_create_user_comment(time_log_params)
      redirect_to time_log_path(@time_log)
    else
      render 'show'
    end
  end

  private
  def time_log_params
    params.require(:time_log).permit(:end_at)
  end

  def target_month
    params[:query].try {|q|
      year = q["date(1i)"]
      month = q["date(2i)"]
      Time.zone.local(year, month) if year && month
    } || Time.zone.now
  end
end

app/views/admin/time_logs/index.html.slim
div= @user.account

div= stringify_seconds @user.monthly_work_seconds(@target_month)

input.small-center(type="button" onclick="location.href='#{edit_admin_user_path(@user)}'" value="Edit")

= form_tag admin_user_time_logs_path(@user), method: :get do
  = date_select :query, :date, use_month_numbers: true, discard_day: true, start_year: @user.newest_year, end_year: @user.oldest_year, selected: @target_month
  = submit_tag "検索"

table
  tr
    th start
    th end
  - @time_logs.reverse_each do |time_log|
    tr
      td= time_log.start_at.to_s
      - if time_log.end_at
        td= link_to time_log.end_at.to_s, admin_time_log_path(time_log)
      - else
        td= link_to "未終了", admin_time_log_path(time_log)

app/views/admin/time_logs/show.html.slim
- if @time_log.errors.any?
  - @time_log.errors.full_messages.each do |message|
    div= message
- if @time_log.original_end_at
  div= form_for [:admin, @time_log] do |f|
    - year = Time.zone.now.year
    = f.datetime_select :start_at, use_month_numbers: true, start_year: year.pred, end_year: year
    | ~ 
    = f.datetime_select :end_at, use_month_numbers: true, start_year: year.pred, end_year: year
    = f.submit "変更"
- else
  div 未完了です

= form_for @time_log.admin_comments.new, url: admin_time_log_comments_path(@time_log) do |f|
  .comment-form
    = f.label :body, "コメント"
    = f.text_field :body, autocomplete: :off, class: "body"
    = f.submit "送信", class: "send"

- @time_log.comments.reverse_each do |comment|
  div
    = comment.body
    - if comment.instance_of? UserComment
      = form_tag admin_comment_path(comment.id), method: :patch, remote: true
        = select_tag "admin_comment[status]", options_for_select({"未承認" => 0, "承認" => 1}, selected: comment.status), onchange: '$(this.form).submit();'