config/routes.rb
Rails.application.routes.draw do
  root "user/time_logs#index"

  resource :admins, only: [:create], controller: "admin/admins" do
    get "signin" => "admin/admins#signin"
    delete "signout" => "admin/admins#signout"
  end

  # for admin
  namespace :admin do
    root "time_logs#index"
    resources :users, only: [:index, :new, :create, :edit, :update] do
      resources :time_logs, only: [:index, :show, :update], shallow: true do
        resources :comments, only: [:create, :update]
      end
    end
  end

  resource :users, only: [:create, :edit, :update], module: :user do
    get "signin" => "users#signin"
    delete "signout" => "users#signout"
  end

  # for logined user
  resources :time_logs, only: [:index, :show, :create, :update], module: :user do
    resources :comments, only: [:create]
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Clockin
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav.nav-bar
      section.logo
        strong Clockin
      - if current_user
        section.nav-section
          = link_to "HOME", time_logs_path
        section.nav-section.signout
          = link_to "Sign out", signout_users_path, method: :delete
    .wrapper
      .notice
        = notice
      .alert
        = alert
      .content
        = yield

app/views/layouts/application_admin.html.slim
doctype html
html
  head
    title
      | Clockin for Admin
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav.nav-bar
      section.logo
        strong Clockin
      - if current_admin
       section.nav-section
         = link_to "Users", admin_users_path
       section.nav-section.signout
         = link_to "Sign out", signout_admins_path, method: :delete
    .wrapper
      .notice
        = notice
      .alert
        = alert
      .content
        = yield